name: Validate

on:
  push: 
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
  validate:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v6"
        - uses: "home-assistant/actions/hassfest@master"
  tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v6"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: pip install -r requirements_test.txt
      - name: Run tests
        run: pytest tests/ -v
